# Generated by Django 5.2.7 on 2025-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='F.creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='F.Actualizacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
