# Generated by Django 5.2.7 on 2025-10-14 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.CreateModel(
            name='MakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30, verbose_name='Titulo')),
                ('detail', models.TextField(verbose_name='Detalle')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='F.Orden')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ordenIMG', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='F.creacion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
