# Generated by Django 5.2.7 on 2025-10-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_alter_category_options_makeorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='makeorder',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AddField(
            model_name='makeorder',
            name='categories',
            field=models.ManyToManyField(to='ot.category', verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='makeorder',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='F.Actualizacion'),
        ),
    ]
